openapi: 3.0.1
info:
  title: Sleep Tracker API V1
  version: v1
  description: API for tracking sleep records and managing social connections
servers:
- url: http://localhost:3000
  description: Development server
paths:
  "/api/v1/auth/login":
    post:
      summary: Login user
      tags:
      - Authentication
      description: Authenticate a user and receive a JWT token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: User ID to authenticate
              required:
              - user_id
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: JWT authentication token
                      user:
                        "$ref": "#/components/schemas/User"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v1/sleep_records":
    get:
      summary: List sleep records
      tags:
      - Sleep Records
      description: Retrieve all personal sleep records with cursor-based pagination
      security:
      - Bearer: []
      parameters:
      - name: cursor
        in: query
        required: false
        schema:
          type: string
        description: Cursor for pagination
      - name: limit
        in: query
        required: false
        schema:
          type: integer
        description: Number of records to return (default 20)
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/SleepRecord"
                  meta:
                    type: object
                    properties:
                      next_cursor:
                        type: string
                        nullable: true
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v1/sleep_records/clock_in":
    post:
      summary: Clock in
      tags:
      - Sleep Records
      description: Record the start of a sleep session
      security:
      - Bearer: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      new_record:
                        "$ref": "#/components/schemas/SleepRecord"
                      sleep_records:
                        type: array
                        items:
                          "$ref": "#/components/schemas/SleepRecord"
        '422':
          description: unprocessable_content
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v1/sleep_records/clock_out":
    post:
      summary: Clock out
      tags:
      - Sleep Records
      description: Record the end of a sleep session
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      sleep_record:
                        "$ref": "#/components/schemas/SleepRecord"
        '422':
          description: unprocessable_content
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v1/sleep_records/friends_weekly":
    get:
      summary: Friends weekly sleep records
      tags:
      - Sleep Records
      description: Get friends' sleep records from the previous week, sorted by duration
      security:
      - Bearer: []
      parameters:
      - name: cursor
        in: query
        required: false
        schema:
          type: string
        description: Cursor for pagination
      - name: limit
        in: query
        required: false
        schema:
          type: integer
        description: Number of records to return (default 20)
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/SleepRecord"
                  meta:
                    type: object
                    properties:
                      next_cursor:
                        type: string
                        nullable: true
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v1/follows":
    post:
      summary: Follow user
      tags:
      - Follows
      description: Follow another user
      security:
      - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                followee_id:
                  type: integer
                  description: ID of the user to follow
              required:
              - followee_id
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      follow:
                        "$ref": "#/components/schemas/Follow"
        '422':
          description: unprocessable_content
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v1/follows/{followee_id}":
    delete:
      summary: Unfollow user
      tags:
      - Follows
      description: Unfollow a user
      security:
      - Bearer: []
      parameters:
      - name: followee_id
        in: path
        required: true
        schema:
          type: integer
        description: ID of the user to unfollow
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                      unfollow:
                        "$ref": "#/components/schemas/Follow"
        '422':
          description: unprocessable_content
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    SleepRecord:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        user_name:
          type: string
        duration:
          type: integer
          nullable: true
        status:
          type: string
        clock_in_time:
          type: string
          format: date-time
        clock_out_time:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
    Follow:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        followee_id:
          type: integer
        created_at:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: object
          properties:
            message:
              type: string